### PR TITLE
Make `StaticFloat64 <: Real`

### LINKED ISSUE #66: Un-breaking functions requiring `<:Real`
Now that `StaticFloat64 <: Real` is false, lots of functions that are defined independently of Static.jl are breaking. More concretely, suppose
```julia
foo(x::Real)
```
is defined in a package that does _not_ depend on Static.jl. Passing a `StaticFloat64` to `foo` now throws an `MethodError`. 

For packages I control, there's an easy fix: Change the constraint to `::Number` or remove it altogether. But what's the recommended approach for packages I can't change so easily?

The only easy fix I see is to define a local `_foo(x) = foo(x)`, add a method `_foo(::StaticFloat64{x}) where {x}`, and then always call `_foo`. But that seems like a mess, and it will still break downstream when users of _my_ package try to call `foo`. Any other ideas?

### PR DESCRIPTION
**Pull request by Tokazama**
This doesn't fully resolve #66, but it at least get's some functionality back that @cscherrer might be missing.

### CODE REVIEW

**Comment by cscherrer** [comment]
Thank you!! Check it out @oschulz

**Comment by Tokazama** [comment]
Note that subtyping `AbstractFloat` did cause invalidations so if that's really what is needed it will probably take PRs to Base.

**Comment by cscherrer** [comment]
I think `Real` will probably be enough. We'll test this with MeasureBase and MeasureTheory, it would be great to be able to use the latest Static.jl again!

**Comment by oschulz** [comment]
Merci, that should help a lot! I don't think we need `<: AbstractFloat`, as @cscherrer says `<: Real` should be fully sufficient.

**Comment by Tokazama** [comment]
Good to hear. Sorry it's taken so long.

**Comment by cscherrer** [comment]
No worries! We appreciate your work on this :) 

@Tokazama what are you doing these days for `Base.OneTo`? This code now throws an error:
```julia
@inline function logdensity_def(
    d::PowerMeasure{M,NTuple{N,Base.OneTo{StaticInt{0}}}},
    x,
) where {M,N}
    static(0.0)
end
```
There are some little things like this around. Maybe changing dispatch patterns could make it so the problem just doesn't come up, but I'm not sure. In case it's not obvious, this is to handle the degenerate case. A "power measure" is a product of the same measure some number of times. We have these set up to mimic the structure of a FillArray type. In this particular method, one of the axes is statically known to be empty, in which case the logdensity is (static) zero.

**Comment by Tokazama** [comment]
The best approach might be to move the optionally static ranges from ArrayInterface here, but we haven't really formally approached the topic as a group yet.

**Comment by cscherrer** [comment]
Currently we're doing this
```julia
@inline function powermeasure(x::T, sz::Tuple{Vararg{<:Any,N}}) where {T,N}
    a = axes(Fill{T,N}(x, sz))
    A = typeof(a)
    PowerMeasure{T,A}(x, a)
end
```
So literally just like a FillArray. Maybe we should instead be using `ArrayInterface.axes` and `ArrayInterface.axes_types`? I still don't really understand how ArrayInterface connects to other packages, or where things are going.

**Comment by Tokazama** [comment]
> So literally just like a FillArray. Maybe we should instead be using ArrayInterface.axes and ArrayInterface.axes_types? I still don't really understand how ArrayInterface connects to other packages, or where things are going.

I still need to figure the best path forward falling the triage about `StaticInt`.

**Comment by Tokazama** [comment]
I don't quite understand the output for invalidation tests here but I didnt have any new one on 1.8.2.

**Comment by oschulz** [comment]
Thanks a *lot* for this @Tokazama !

**Comment by oschulz** [comment]
> I still need to figure the best path forward falling the triage about StaticInt.

The issue was that `StaticInt <: Integer` is problematic due to lot's of invalidations, right?

**Comment by Tokazama** [comment]
> > I still need to figure the best path forward falling the triage about StaticInt.
> 
> The issue was that `StaticInt <: Integer` is problematic due to lot's of invalidations, right?

That was the biggest issue, but there were a lot of things causing invalidations prior to the switch from `StaticInt <: Integer`.

**Comment by oschulz** [comment]
So should I take a look at what happens if we do `StaticInt <: Integer` in the current state of things?

**Comment by Tokazama** [comment]
Help is always welcome! It might be a while until we can freely subtype `Integer` though since we still get a lot of invalidations https://github.com/SciML/Static.jl/issues/73#issuecomment-1299518793.

**Pull request merged**
