### PR TITLE
Define basic "static" interface

### PR DESCRIPTION
**Pull request by Tokazama**

### CODE REVIEW

**Comment by Tokazama** [comment]
@chriselrod , I figured this one was public facing enough that you might want to review it.

**Comment by chriselrod** [comment]
It'd be convenient to have a `known` that works as the identity for non-static types, to make it easier to write code where inputs may or may not be static.

**Comment by Tokazama** [comment]
What about a counterpart to `static`, which ensures everything is a static type. Something like `dynamic` that ensures everything is "dynamic". Not sure if there's a better word than "dynamic" b/c in my head "dynamic" sounds like something that's mutable and potentially unsafe for a lot of operations. Maybe "fixed"....?

**Comment by chriselrod** [comment]
I don't mind `dynamic`, but keep using names like `unwrap` for that. `unbox` is another option. But they make `Static*` sound like a container / speak more about structure than what's being done and why. So I think I like `dynamic` more.
But maybe just using `Int`/`Bool`/`Symbol`/etc explicitly is the way to go.
We're probably not mixing between them, so one function to work on any static isn't needed. They're also explicit about the behavior and entirely non-mysterious to anyone reading.
Perhaps `Int` and friends should be defined on `::Type{StaticInt{N}}` as well, and similarly for the others?

**Comment by Tokazama** [comment]
After sleeping for a couple hours, `dynamic` is really starting to grow on me. I don't think `unwrap` or `unbox` are bad, but `dynamic` really does seem more appropriate than anything else.

> We're probably not mixing between them, so one function to work on any static isn't needed. They're also explicit about the behavior and entirely non-mysterious to anyone reading.

I think the utility of `known` and `dynamic` is currently most obvious when working with tuples of mixed "static" and "dynamic" types. It's not hard to role your own code for this, but it's nice to have. It's also nice to have some sort of standard in case people build on this.

> Perhaps `Int` and friends should be defined on `::Type{StaticInt{N}}` as well, and similarly for the others?

I did stuff like this in the past and got weird reactions when sharing code. I can't think of anything inherently wrong with it though. If it's something you're really keen on I'm happy to add it in.

**Comment by Tokazama** [comment]
Let me know if this satisfies your previous concerns/comments.

**Review by chriselrod — APPROVED** [review]
Looks good to me.

**Pull request merged**
