### PR TITLE
Add another missing NamedTuple getindex method for StaticSymbol

### LINKED ISSUE #124: Another missing `getindex` method for NamedTuple and StaticSymbol
**Describe the bug 🐞**

Similar to https://github.com/SciML/Static.jl/issues/120, given the README, I expected to use StaticSymbols like symbols, but one more method is missing: `nt[(static(:a), static(:b))]` where nt is a NamedTuple.

**Expected behavior**

```julia
nt = (a=1,b=2,c=2)
nt[(static(:a),static(:b))]
```
should return `(a = 1, b = 2)` as with regular Symbols.

**Minimal Reproducible Example 👇**

Without MRE, we would only be able to help you to a limited extent, and attention to the issue would be limited. to know more about MRE refer to [wikipedia](https://en.wikipedia.org/wiki/Minimal_reproducible_example) and [stackoverflow](https://stackoverflow.com/help/minimal-reproducible-example).

```julia
nt = (a=1,b=2,c=2)
nt[(static(:a),static(:b))]
```

**Error & Stacktrace ⚠️**

```julia
ERROR: MethodError: no method matching getindex(::@NamedTuple{a::Int64, b::Int64, c::Int64}, ::Tuple{StaticSymbol{:a}, StaticSymbol{:b}})
```

**Environment (please complete the following information):**

  - Output of `using Pkg; Pkg.status()`

```julia
Status `/private/var/folders/qz/zw4jl7jx2zgdcsj_6xhrkcmr0000gp/T/jl_2oOGdg/Project.toml`
  [aedffcd0] Static v0.8.9
```

  - Output of `using Pkg; Pkg.status(; mode = PKGMODE_MANIFEST)`

```julia
Status `/private/var/folders/qz/zw4jl7jx2zgdcsj_6xhrkcmr0000gp/T/jl_2oOGdg/Manifest.toml`
  [615f187c] IfElse v0.1.1
  [aedffcd0] Static v0.8.9
```

  - Output of `versioninfo()`

```julia
Julia Version 1.10.0
Commit 3120989f39b (2023-12-25 18:01 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 10 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores
Environment:
  LD_LIBRARY_PATH = :/opt/homebrew/Cellar/r/4.2.1_4/lib/R/lib
```

**Additional context**

Thanks for fixing that last one so quickly by the way!

### PR DESCRIPTION
**Pull request by ianfiske**
Fixes #124 .  This addresses the need to do

```julia
nt = (a=1, b=2, c=3)
nt[(static(:a), static(:b))]
```

This is a follow-up to https://github.com/SciML/Static.jl/issues/120 and https://github.com/SciML/Static.jl/pull/121.

As noted in https://github.com/SciML/Static.jl/pull/121, the Aqua tests currently fail, but the tests pass otherwise.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
This test failure is real though. Fix the ambiguity? But I don't know if you can do that without piracy.

**Comment by ianfiske** [comment]
> This test failure is real though. Fix the ambiguity? But I don't know if you can do that without piracy.

Yeah, the Aqua suggestion to implement
```
 getindex(::NamedTuple, ::Tuple{})
```
is clearly type piracy, so I'm thinking we should avoid it.  But what is the fix?  Should I submit at PR to julia base to implement `getindex(::NamedTuple, ::Tuple{})` there?  Not ideal due to the wait for it to be merged there and released, etc, but if you think this is the path forward, I'll submit a PR.

**Comment by Tokazama** [comment]
Have you tried specifying at least one element for the tuple (`Tuple{<:StaticSymbol, Vararg{<:StaticSymbol}}`)?

**Comment by ianfiske** [comment]
> Tuple{<:StaticSymbol, Vararg{<:StaticSymbol}}

With 
```julia
function Base.getindex(x::NamedTuple, symbols::Tuple{<:StaticSymbol, Vararg{<:StaticSymbol}}) where {N}
    return x[map(known, symbols)]
end
```

I get 
```
┌ Static
│  WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
│  You may need to write `f(x::Vararg{T})` rather than `f(x::Vararg{<:T})` or `f(x::Vararg{T}) where T` instead of `f(x::Vararg{T} where T)`.
```

But this warning goes away with 
```julia
function Base.getindex(x::NamedTuple, symbols::Tuple{StaticSymbol, Vararg{StaticSymbol}})
    return x[map(known, symbols)]
end
```

**Comment by ChrisRackauckas** [comment]
@ArnoStrouwen what does this mean? https://github.com/SciML/Static.jl/actions/runs/7841889229/job/21399128321?pr=123#step:6:1049

**Comment by ArnoStrouwen** [comment]
My guess would be it fails because dev version of Static gets added to the SciMLBase project here:
https://github.com/SciML/Static.jl/actions/runs/7841889229/job/21399128321?pr=123#step:6:1049
However, Static is normally not a part of SciMLBase, hence Aqua complains it is a stale dep and has no compat entry.

**Comment by ArnoStrouwen** [comment]
I can't think of anything besides moving it out of the core group into its own group, which is then not ran here.

**Comment by ChrisRackauckas** [comment]
Yeah let's just make a QA group.

**Pull request merged**
