### PR TITLE
isinteger for StaticFloat64

### PR DESCRIPTION
**Pull request by jishnub**
After this,
```julia
isinteger(1.0) == isinteger(static(1.0))
```

### CODE REVIEW

**Comment by jishnub** [comment]
Oddly, the format check fails on master for me

**Comment by ChrisRackauckas** [comment]
What are the invalidations introduced by this?

**Comment by jishnub** [comment]
The invalidation test passed, which suggests that there are no new invalidations introduced by this (86 on master as well as on this PR)

**Comment by ChrisRackauckas** [comment]
LoopVectorization doesn't seem to like it?

**Comment by jishnub** [comment]
I think the LoopVectorization test failure is an Aqua formatting issue

**Comment by ChrisRackauckas** [comment]
@chriselrod ?

**Comment by chriselrod** [comment]
> @chriselrod ?

Tests pass locally on Julia master, so things like Aqua not liking PkgExtensions on older Julia versions haven't been a priority.

**Comment by ChrisRackauckas** [comment]
Alrighty, this looks fine then.

**Comment by ChrisRackauckas** [comment]
It does look to just be weird Aqua stuff and nothing really deep. I need to do a clean up pass....

**Comment by chriselrod** [comment]
Tests also passed on this PR locally.
I'll just disable Aqua for Julia < 1.9.

**Pull request merged**
