### PR TITLE
Extend `isinteger(::StaticInt)` (#93)

### PR DESCRIPTION
**Pull request by Tokazama**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Check the invalidations

**Comment by Tokazama** [comment]
> Check the invalidations

It passed invalidation tests so I'm not sure what you mean. Was there a something specific from the invalidation tests you wanted me to see?

**Comment by ChrisRackauckas** [comment]
Didn't see. Cool, then this seems good.

**Comment by jishnub** [comment]
Shouldn't this be for `StaticInteger`s instead of `StaticInt`s? Currently,
```julia
julia> static(true) |> isinteger
ERROR: MethodError: no method matching isinteger(::True)
Closest candidates are:
  isinteger(::Integer) at number.jl:20
  isinteger(::Complex) at complex.jl:145
  isinteger(::Rational) at rational.jl:267
  ...
Stacktrace:
 [1] |>(x::True, f::typeof(isinteger))
   @ Base ./operators.jl:911
 [2] top-level scope
   @ REPL[12]:1

julia> true |> isinteger
true
```
Also, perhaps it should be more general than that, so that something like `static(2.0) |> isinteger` works as well.

**Comment by Tokazama** [comment]
If it doesn't cause anymore invalidations that's probably fine. The fate of `StaticBool` is a bit uncertain to me at the moment. It's sort of a trait that acts like `Bool`

**Pull request merged**
