### PR TITLE
adds the rest of the float intrinsics

### PR DESCRIPTION
**Pull request by JeffreySarnoff**
these functions are available
```
fneg, fabs, fcopysign,
feq, fne, fle, flt,
fadd, fsub, fmul, fdiv, frem,
fmuladd, ffma
```

no additional tests were added

### CODE REVIEW

**Comment by chriselrod** [comment]
I recently had to remove `Base.@pure` from Pumas.
I asked Jameson about the use there (which was fairly similar to the uses here), and he suggested getting rid of it is a good idea.

Maybe we should make a separate PR, and like in https://github.com/SciML/Static.jl/pull/19/files rely on `@inferred` tests to trust in the results.

We'll need to set up some benchmarks, though, because inference tends to seem non-deterministic, so it seems like there's always a chance we'll end up getting inference failures in real code.

**Comment by Tokazama** [comment]
I second the sentiments on `@pure`.

**Comment by JeffreySarnoff** [comment]
I am happy to remove the `@pure` everywhere [I agree that it is inappropriate, however in this case I chose to copy the practice as shown -- no harm, no problem].

**Comment by JeffreySarnoff** [comment]
There remains adding coverage of the new float functions.  Following that, I agree with @chriselrod; the more facile approach lets this PR be well-defined and focused on provision of the float intrinsics.   We expect to open a second PR once this is complete, to use this revision as the underpinning for the more involved testing with @inferred.  Along with that, the repository should have some careful benchmarking to apply as a chooser or refuser of plausibly faster-stabler-memlesser refinement .

**Comment by Tokazama** [comment]
Benchmarks are the key thing here. `@inferred` tests are used pretty aggressively here.

**Comment by JeffreySarnoff** [comment]
What would you like the benchmarking to reveal?

**Comment by Tokazama** [comment]
I may have been a bit misleading when I said "Benchmarks are the key thing here". By "here" I meant in Static.jl. I don't think anything in this PR would have questionable performance since it should all be done at compile time.

My concern with performance in #19 is b/c instead of doing `Base.:(*)(x::Int, y::StaticInt{N}) where {N} = x * N` we aren't specializing on `y`, so it is more like `Base.:(*)(x::Int, @nospecialize(y::StaticInt) where {N} = x * getfield(typeof(x), :parameters)[1]`, but we still want it to be as fast and inferrible as `Base.:(*)(x::Int, y::Int)`. I haven't been able to detect any performance issues with this yet, but occasionally we'll have an odd issue come up with a static type when it is passed through many methods. For example, deeply nested method calls on `StaticInt{N}` occasionally won't be  inferrible.

We should probably just have a separate PR for that entirely because I assume the end produce will be some tricky micro benchmarks and odd corner cases.

**Comment by JeffreySarnoff** [comment]
I am closing this and replacing it with several simpler successive PRs. 
(a) remove `@pure`
(b) add other float intrinsics with simple sanity tests
(c) provide benchmarking

**Pull request closed without merging**
